### ISSUE TITLE
Missing file when updating to 0.3.0 

### ISSUE THREAD

**Issue by Jaysp656** [DropDaDeuce/LethalGargoyles#1]
I'm updating from 0.1.0 to 0.3.0 and am getting this error. I suspect the file wasn't added included when adding to Thunderstore but I have no knowledge of that process. Seems like a cool mod though and I hope to use the newest updates when I'm able. Sticking to 0.1.0 for now.

`The original error might provide hints about what went wrong: Failed to copy file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\{UserName}\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\New Monsters - Less Serious\BepInEx\plugins\DropDaDeuce-LethalGargoyles\LethalGargoyles\Voice Lines\Taunt - Prior Death\Coroner\taunt_priordeath_EnemyButlerExplode.ogg'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost) at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1() at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func\``1 runFunc)
`

**Comment by DropDaDeuce** [comment]
The file is definitely in the Thunderstore package, but I wonder if there might be an issue updating from v0.1.0 to v0.3.0. Have you tried uninstalling and reinstalling? I'll look into the specific cause in the mean time. Thank you for reporting!

**Comment by DropDaDeuce** [comment]
I can't seem to replicate this on my end, if you are using a mod manager, can you share a profile code? Else a list of the mods you're running would work also. Also, at what point are you getting this error? I assume when starting a game as host?

**Comment by Jaysp656** [comment]
Yes, I tried uninstalling then reinstalling. The error just happens when I click to update the mod in the modpack in Thunderstore. If I run the game it works fine with version 0.1.0. I think it mist be some issue with my modpack, either my specific copy of it or maybe another mod somehow affecting things. If I try updating it in my other modpack it updated just fine but not in this one

I have a profile code here 0193c3df-2138-41c4-a26d-8555ff39097a

**Comment by DropDaDeuce** [comment]
Could be the mod manager, also. I've heard some things about TMM, but I haven't used it myself to validate the feedback I hear. I imported your code into my mod manager (Gale Mod Manager). It took a moment to download lol, but it worked fine! I saw it was on version 0.1.0 of lethal gargoyles, so I updated to v0.3.0, and it updated without an issue. I was able to start the game and play. Not sure why TMM is throwing a fit.

**Comment by Jaysp656** [comment]
Hmm, okay. That is odd. Maybe TMM is downloading it in an odd way or something so it looks for the file before it places it or deletes it midway. Hopefully I can figure it out. Thanks for taking a look!

Also I hadn't heard of Gale Mod Manager so I'll take a look at that as well.

**Comment by DropDaDeuce** [comment]
No problem! Hopefully you're able to get it sorted. I'll mark this as complete. Reach out if you have any other questions!
